---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "sudo"} # To enable elevated command.
      - {name: "openssh-server"} # To enable SSH.
      - {name: "sshpass"} # noninteractive ssh password provider.
      - {name: "qemu-guest-agent"} # To enhance Proxmox integration with the VM.
      - {name: "python3-pip"}
      - {name: "python-is-python3"}
      - {name: "pip"} # A tool for installing and managing Python packages.
      - {name: "libsecret-tools"} # Store and retrieve passwords.
      - {name: "uuid"} # Universally Unique Identifier Command-Line Tool.
      - {name: "ufw"} # A program for managing the firewall for the VM.
