---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "sudo"} # To enable elevated command.
      - {name: "qemu-guest-agent"} # To enhance Proxmox integration with the VM.
      - {name: "openssh-server"} # To enable SSH.
      - {name: "cloud-init"} # To enable cloud-init.
      - {name: "python-is-python3"}
      - {name: "pipx"} # A tool for installing and managing Python packages.
