---
- name: "Removing unnecessary packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: false
    packages:
      - {name: "unattended-upgrades", state: "absent"}

- name: "Removing dependencies that are no longer required"
  ansible.builtin.apt:
    autoremove: true

- name: "Removing unnecessary packages from the cache"
  ansible.builtin.apt:
    autoclean: true
